import type { Machine, User } from '../types';
import { MachineStatus } from '../types';

export const INITIAL_MACHINES: Machine[] = [
  {
    id: 'M-01',
    name: 'Conf. China 1',
    brand: 'China',
    type: 'CONFORMADORA',
    category: 'STANDARD',
    status: MachineStatus.IDLE,
    efficiency: 92,
    oee_availability: 95,
    oee_performance: 97,
    oee_quality: 99,
    operatorIds: ['U-002'],
    currentJobId: null,
    isActive: true,
    lastMaintenance: '2023-10-01',
    color: '#10b981',
    totalMetersProduced: 12000,
    nextMaintenanceMeters: 15000,
  },
  {
    id: 'M-02',
    name: 'Conf. Cunmac',
    brand: 'Cunmac',
    type: 'CONFORMADORA',
    category: 'STANDARD',
    status: MachineStatus.IDLE,
    efficiency: 0,
    oee_availability: 0,
    oee_performance: 0,
    oee_quality: 0,
    operatorIds: [],
    currentJobId: null,
    isActive: true,
    lastMaintenance: '2023-09-15',
    color: '#f59e0b',
    totalMetersProduced: 8000,
    nextMaintenanceMeters: 10000,
  },
  {
    id: 'M-03',
    name: 'Conf. Framemac',
    brand: 'Framemac',
    type: 'CONFORMADORA',
    category: 'STANDARD',
    status: MachineStatus.IDLE,
    efficiency: 88,
    oee_availability: 90,
    oee_performance: 95,
    oee_quality: 98,
    operatorIds: ['U-004'],
    currentJobId: null,
    isActive: true,
    lastMaintenance: '2023-10-10',
    color: '#06b6d4',
    totalMetersProduced: 15000,
    nextMaintenanceMeters: 20000,
  },
  {
    id: 'M-06',
    name: 'Taller Herrería',
    brand: 'Interno',
    type: 'HERRERIA',
    status: MachineStatus.IDLE,
    efficiency: 100,
    oee_availability: 100,
    oee_performance: 100,
    oee_quality: 100,
    operatorIds: ['U-004'],
    currentJobId: null,
    isActive: true,
    color: '#f97316',
    totalMetersProduced: 0,
    nextMaintenanceMeters: 0,
  },
  {
    id: 'M-07',
    name: 'Estación Panelizado',
    brand: 'Pinnacle',
    type: 'PANELIZADO',
    status: MachineStatus.IDLE,
    efficiency: 100,
    oee_availability: 100,
    oee_performance: 100,
    oee_quality: 100,
    operatorIds: ['U-003'],
    currentJobId: null,
    isActive: true,
    color: '#8b5cf6',
    totalMetersProduced: 0,
    nextMaintenanceMeters: 0,
  },
  {
    id: 'M-CARGA',
    name: 'Unidad de Despacho',
    brand: 'Logística',
    type: 'CARGA',
    status: MachineStatus.IDLE,
    efficiency: 100,
    oee_availability: 100,
    oee_performance: 100,
    oee_quality: 100,
    operatorIds: [],
    currentJobId: null,
    isActive: true,
    color: '#3b82f6',
    totalMetersProduced: 0,
    nextMaintenanceMeters: 0,
  },
];

export const INITIAL_USERS: User[] = [
  { id: 'U-001', name: 'Admin Principal', role: 'ADMIN', pin: '1234' },
  { id: 'U-002', name: 'Juan Perez', role: 'OPERATOR', pin: '0000' },
  { id: 'U-003', name: 'Maria Gomez', role: 'OPERATOR', pin: '1111' },
  { id: 'U-004', name: 'Carlos Diaz', role: 'OPERATOR', pin: '2222' },
];

export const INITIAL_CATALOG = [
  { sku: 'P-M70', name: 'Perfil Montante 70', description: 'Perfil galvanizado para tabiquería' },
  { sku: 'P-S70', name: 'Perfil Solera 70', description: 'Perfil galvanizado base' },
];
